#' Load and parse eyelink `.asc` file
#'
#' todo: description goes here...
#'
#' @param file An SR Research EyeLink `.asc` file generated by the official
#' EyeLink `edf2asc` command.
#'
#' @return A numeric vector giving number of characters (code points) in each
#'    element of the character vector. Missing string have missing length.
#'
#' @seealso [eyelinker::read.asc()] which this function wraps.
#'
#' @examples
#' \dontrun{
#' system.file("extdata", "assocret.asc", package = "eyeris") |>
#'   eyeris::load()
#' }
#'
#' @export
load <- function(file) {
  if (!tools::file_ext(file) %in% c("asc", "gz")) {
    stop(sprintf("Error: The file '%s' is not a .asc file.", file))
  }

  x <- eyelinker::read.asc(
    fname = file,
    samples = TRUE,
    events = TRUE,
    parse_all = FALSE
  )

  # parse metadata
  is_mono <- x$info$mono
  is_left <- x$info$left
  is_right <- x$info$right
  if (is_mono) {
    if (is_left) eye <- "L"
    if (is_right) eye <- "R"
  } else {
    if (is_left && is_right) eye <- "LR"
  }

  hz <- x$info$sample.rate

  pupil_type <- tolower(x$info$pupil.dtype)

  x$raw <- x$raw |>
    dplyr::select(
      time_orig = time,
      pupil_raw = ps,
      eye_x = xp,
      eye_y = yp
    ) |>
    dplyr::mutate(
      eye = eye,
      hz = hz,
      type = pupil_type
    ) |>
    dplyr::relocate(pupil_raw, .after = type)

  list_out <- vector("list", length = 6)

  names.out <- c(
    "file",
    "timeseries",
    "events",
    "blinks",
    "info",
    "latest"
  )

  names(list_out) <- names.out

  list_out$file <- file
  list_out$timeseries <- x$raw
  list_out$events <- x$msg
  list_out$blinks <- x$blinks
  list_out$info <- x$info
  list_out$latest <- "pupil_raw"

  class(list_out) <- "eyeris"

  return(list_out)
}
